// ACTION TYPES FOR MODELS

// FOR SIGNIN MODAL
export const OPEN_SIGNIN_MODAL = 'OPEN_SIGNIN_MODAL';
export const SET_SIGNIN_MODAL_FLAG = 'SET_SIGNIN_MODAL_FLAG';
export const CLOSE_SIGNIN_MODAL = 'CLOSE_SIGNIN_MODAL';

// FOR SUCCESS MODAL
export const OPEN_SUCCESS_MODAL = 'OPEN_SUCCESS_MODAL';
export const CLOSE_SUCCESS_MODAL = 'CLOSE_SUCCESS_MODAL';

// FOR VIDEO MODAL

export const OPEN_VIDEO_MODAL = 'OPEN_VIDEO_MODAL';
export const CLOSE_VIDEO_MODAL = 'CLOSE_VIDEO_MODAL';

// SOCIAL FEED

export const GET_INSTAGRAM_DATA = 'GET_INSTAGRAM_DATA';
export const GET_INSTAGRAM_DATA_SUCCESS = 'GET_INSTAGRAM_DATA_SUCCESS';
// USER AUTH
export const CHECK_USERNAME_AVAILIBILITY = 'CHECK_USERNAME_AVAILIBILITY';
export const CHECK_USERNAME_AVAILIBILITY_SUCCESS =
  'CHECK_USERNAME_AVAILIBILITY_SUCCESS';
export const STORE_USERNAME_ON_CHECK_AVAILAIBILITY =
  'STORE_USERNAME_ON_CHECK_AVAILAIBILITY';
export const RECOVERY_KEY_CHANGED = 'RECOVERY_KEY_CHANGED';
export const STORE_USER_PASSWORD = 'STORE_PASSWORD';
export const USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED';
export const STORE_USER_EMAIL = 'STORE_EMAIL';
export const STORE_USER_CONFIRMPASSWORD = 'STORE_CONFIRMPASSWORD';
export const ON_CREATE_USER_ID = 'ON_CREATE_USER_ID';
export const CREATE_USER_ID_SUCCESS = 'CREATE_USER_ID_SUCCESS';
export const GET_BALANCE = 'GET_BALANCE';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const FORM_VALIDATOR_ON_CHECK_USER = 'FORM_VALIDATOR_ON_CHECK_USER';
export const STORE_USER_MNEMONIC_ON_SIGN_UP = 'STORE_USER_MNEMONIC_ON_SIGN_UP';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_REQUEST_SUCCESS = 'SIGN_IN_REQUEST_SUCCESS';
export const DISABLED_INPUTS = 'DISABLED_INPUTS';
export const DISPLAY_ERROR_MESSAGE = 'DISPLAY_ERROR_MESSAGE';
export const SIGN_IN_REQUEST_ERROR = 'SIGN_IN_REQUEST_ERROR';
export const CREATE_PASSWORD_CHANGED = 'CREATE_PASSWORD_CHANGED';
export const CONFIRM_CREATE_PASSWORD_CHANGED =
  'CONFIRM_CREATE_PASSWORD_CHANGED';
export const USER_EMAIL_CHANGED = 'STORE_EMAIL_CHANGED';
export const GET_DAPPS = 'GET_DAPPS';
export const SET_DAPPS = 'SET_DAPPS';
export const CLEAR_STORED_USERNAME = 'CLEAR_STORED_USERNAME';
export const CLEAR_CREATE_ID_DATA = 'CLEAR_CREATE_ID_DATA';
export const PAYMENT_MESSAGE = 'PAYMENT_MESSAGE';

// ACTION TYPES FOR PROFILE PAGE
export const STORE_PASSWORD_FOR_ANOTHER_ACCOUNT =
  'STORE_PASSWORD_FOR_ANOTHER_ACCOUNT';
export const CLEAR_STORE_PASSWORD_FOR_ANOTHER_ACCOUNT =
  'CLEAR_STORE_PASSWORD_FOR_ANOTHER_ACCOUNT';
export const SHOW_API_RESPONSE = 'SHOW_API_RESPONSE';
export const CHECK_USER_PASSWORD = 'CHECK_USER_PASSWORD';
export const PROFILE_IMAGE_CHANGED = 'PROFILE_IMAGE_CHANGED';
export const UPLOAD_PROFILE_PICTURE = 'UPLOAD_PROFILE_PICTURE';
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const CREATE_ANOTHER_ACCOUNT_SUCCESS =
  'CREATE_ANOTHER_ACCOUNT_SUCCESS';
export const CLEAR_PASSWORD = 'CLEAR_PASSWORD';

// ACTIONS TYPE FOR AUTH PROFILE PAGES
export const STORE_CURRENT_PASSWORD = 'STORE_CURRENT_PASSWORD';
export const STORE_NEW_PASSWORD = 'STORE_NEW_PASSWORD';
export const STORE_CONFIRM_PASSWORD = 'STORE_CONFIRM_PASSWORD';
export const CLEAR_STORED_PASSWORD = 'CLEAR_STORED_PASSWORD';
export const ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD';
export const DISABLED_BUTTON = 'DISABLED_BUTTON';
export const RECOVER_WALLET = 'RECOVER_WALLET';
export const RECOVER_WALLET_SUCCESS = 'RECOVER_WALLET_SUCCESS';
export const STORE_ADDRESS_OF_SENDER = 'STORE_ADDRESS_OF_SENDER';
export const STORE_ADDRESS_OF_RECIEVER = 'STORE_ADDRESS_OF_RECIEVER';
export const STORE_WALLET_AMMOUNT = 'STORE_WALLET_AMMOUNT';
export const STORE_PASSWORD_ON_SEND_TOKKEN = 'STORE_PASSWORD_ON_SEND_TOKKEN';
export const CLEAR_SEND_TOKKEN_DATA = 'CLEAR_SEND_TOKKEN_DATA';
export const SEND_TOKKEN_DATA = 'SEND_TOKKEN_DATA';
export const RECOVER_KEY = 'RECOVER_KEY';
export const RECOVER_KEY_SUCCESS = 'RECOVER_KEY_SUCCESS';
export const SET_GO_ACTION = 'SET_GO_ACTION';
export const SET_GO_ACTION_SUCCESS = 'SET_GO_ACTION_SUCCESS';
export const GET_PAYMENT = 'GET_PAYMENT';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const ALA_COIN_ID_CHANGED = 'ALA_COIN_ID_CHANGED';
export const STRIPE_TOKEN_CHANGED = 'STRIPE_TOKEN_CHANGED';
export const DISPLAY_PAYMENT = 'DISPLAY_PAYMENT';
export const CHECK_FOR_ANOTHER_ID = 'CHECK_FOR_ANOTHER_ID';
export const WRONG_PASSWORD_AT_ADD_ACCOUNT = 'WRONG_PASSWORD_AT_ADD_ACCOUNT';
export const CLEAR_CHANGE_PASSWORD_DATA = 'CLEAR_CHANGE_PASSWORD_DATA';
export const CLEAR_ANOTHER_ID_DATA = 'CLEAR_ANOTHER_ID_DATA';
export const STORE_TRANSACTION_ID = 'STORE_TRANSACTION_ID';
export const SET_ACCOUNT_NO = 'SET_ACCOUNT_NO';
export const RESET_AUTH = 'RESET_AUTH';
export const ALA_AMOUNT_CHANGED = 'ALA_AMOUNT_CHANGED';
export const USER_NAME_CHANGED = 'USER_NAME_CHANGED';
export const SEND_TOKEN_ERROR = 'SEND_TOKEN_ERROR';
export const BUY_ALA_ERROR = 'BUY_ALA_ERROR';
export const CLEAR_AMOUNT = 'CLEAR_AMOUNT'; 
export const GET_ACCOUNT_DETAILS = "GET_ACCOUNT_DETAILS";
export const GET_ACCOUNT_DETAILS_SUCCESS = "GET_ACCOUNT_DETAILS_SUCCESS";
export const CPU_STAKE_AMOUNT_CHANGED="CPU_STAKE_AMOUNT_CHANGED";
export const NET_STAKE_AMOUNT_CHANGED="NET_STAKE_AMOUNT_CHANGED";
export const CLEAR_STAKE_AMOUNTS="CLEAR_STAKE_AMOUNTS";


// ACTIONS TYPE FOR API END POINT
export const SAVE_API_END_POINT = 'SAVE_API_END_POINT';

// ACTIONS TYPE FOR REGISTER DAPP

export const DAPP_NAME_CHANGED = 'DAPP_NAME_CHANGED';
export const DAPP_NAME_AVAILABILITY = 'DAPP_NAME_AVAILABILITY';
export const DAPP_NAME_AVAILABILITY_SUCCESS = 'DAPP_NAME_AVAILABILITY_SUCCESS';
export const DAPP_URL_CHANGED = 'DAPP_URL_CHANGED';
export const DAPP_EMAIL_ID_CHANGED = 'DAPP_EMAIL_ID_CHANGED';
export const DAPP_STORAGE_CHANGED = 'DAPP_STORAGE_CHANGED';
export const DAPP_CATEGORY_CHANGED = 'DAPP_CATEGORY_CHANGED';
export const DAPP_DETAILS_CHANGED = 'DAPP_DETAILS_CHANGED';
export const DAPP_TOKEN_CHANGED = 'DAPP_TOKEN_CHANGED';
export const POST_REGISTER_DAPP_REQUEST = 'POST_REGISTER_DAPP_REQUEST';
export const INCORRECT_RECOVERY_CODE_AT_REDIRECT =
  'INCORRECT_RECOVERY_CODE_AT_REDIRECT';
export const RESET_DAPP = 'RESET_DAPP';
export const GET_DAPP_DETAIL = 'GET_DAPP_DETAIL';
export const GET_DAPP_DETAIL_SUCCESS = 'GET_DAPP_DETAIL_SUCCESS';
export const EDIT_DAPP = 'EDIT_DAPP';
export const DAPP_IMAGES = 'DAPP_IMAGES';


// ADDITIONAL ACTIONS
export const SHOW_LOADER = 'SHOW_LOADER';

// FILE MANAGER
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const FILE_LOADER = 'FILE_LOADER';

